### ISSUE TITLE
how to use it ?

### ISSUE THREAD

**Issue by ctf0** [mohsen1/posthtml-favicons#11]
am trying to test it but sadly without any luck
- tree
```
┗ dist
┗ icons
┗ icon.png
┗ index.html
```

- some code
```html
<html>

    <head>
        <link href="icon.png"
              rel="icon">
    </head>

</html>
```

- setup
```js
posthtml()
    .use(
        favIconPlugin({
            outDir:"/Users/abc/bla/dist"
            configuration: {
                path:"/Users/abc/bla/icons"
            }
        })
    )
    .process(html)
    .then((res) => {
        // files are written to dist folder
        // res.html has new tags
    });
```

- error
```
no such file or directory, open '/icon.png'
```

any help is appreciated.

**Comment by mohsen1** [comment]
try using a relative href

**Comment by ctf0** [comment]
nothing changes, using `<link href="./icon.png" rel="icon">` instead still gives the same error.

btw am using the plugin through vscode which is very similar to how https://github.com/mohsen1/posthtml-favicons#example is,
am not really sure if this matters or not but i think it should work as expected if it is searching in a relative path or is it not ?

**Comment by ctf0** [comment]
here is the ext if u want to test with https://github.com/ctf0/vscode-auto-posthtml-utils
